//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using OnlineFIR.WebApp.Models.ViewModel;
namespace OnlineFIR.WebApp.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineFIRDBEntities : DbContext
    {
        public OnlineFIRDBEntities()
            : base("name=OnlineFIRDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<complaints_tbl> complaints_tbls { get; set; }
        public virtual DbSet<fir_tbl> fir_tbls { get; set; }
        public virtual DbSet<police_station_tbl> police_station_tbls { get; set; }
        public virtual DbSet<updates_tbl> updates_tbls { get; set; }
        public virtual DbSet<user_tbl> user_tbls { get; set; }
    
        public virtual ObjectResult<getFIRDetails_Result> getFIRDetails(string spId)
        {
            var spIdParameter = spId != null ?
                new ObjectParameter("spId", spId) :
                new ObjectParameter("spId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getFIRDetails_Result>("getFIRDetails", spIdParameter);
        }
    
        public virtual ObjectResult<getFIRDetails_Result> getFIRDetailsFromStatus(string spStatus)
        {
            var spStatusParameter = spStatus != null ?
                new ObjectParameter("spStatus", spStatus) :
                new ObjectParameter("spStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getFIRDetails_Result>("getFIRDetailsFromStatus", spStatusParameter);
        }
    
        public virtual ObjectResult<getSingleFIR_Result> getSingleFIR(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSingleFIR_Result>("getSingleFIR", param1Parameter);
        }
    
        public virtual ObjectResult<EditPoliceStation> getStationDetails(string spId)
        {
            var spIdParameter = spId != null ?
                new ObjectParameter("spId", spId) :
                new ObjectParameter("spId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditPoliceStation>("getStationDetails", spIdParameter);
        }
    }
}
