//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFIR.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class police_station_tbl
    {
        public string station_id { get; set; }
        public string user_id { get; set; }
        public string station_name { get; set; }
        public string station_address { get; set; }
        public string station_incharge { get; set; }
        public string station_contact_no { get; set; }
    }
}
