//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFIR.WebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class updates_tbl
    {
        public int update_id { get; set; }
        public string fir_id { get; set; }
        public string last_update { get; set; }
        public string comments { get; set; }
    }
}
